#!/bin/sh
set -e

echo "Running checks..."

for dir in core src-shared src-ipc src-service src-tauri src-auto-auth tests-e2e; do
  echo "Executing $dir"
  (
    cd "$dir"
    echo "Format $dir"
    cargo fmt
    echo "Check $dir"
    cargo check
    echo "Clippy $dir"
    cargo clippy --all-targets --all-features -- -D warnings
    echo "Test $dir"
    cargo test
  )
done

echo "All checks passed!"
