// Generated by Claude.

use core::f64;
use std::time::Duration;

pub struct DownloadSpeedEstimator {
    /// Smoothed bytes per second (exponential moving average).
    bytes_per_second: f64,
    /// EMA smoothing factor in 0..=1. Lower values = smoother.
    alpha: f64,
}

impl DownloadSpeedEstimator {
    /// Create a new estimator.
    /// `alpha` controls how quickly the estimate reacts to new samples.
    /// A value around 0.2–0.3 works well for download progress bars.
    pub const fn new(alpha: f64) -> Self {
        Self {
            bytes_per_second: 0.0,
            alpha: alpha.clamp(0.0, 1.0),
        }
    }

    /// Feed a sample of (`bytes_downloaded`, `time_passed`) for the most recent interval.
    /// `time_passed` is in seconds.
    pub fn update(&mut self, bytes_downloaded: usize, time_passed: Duration) {
        if time_passed <= Duration::ZERO {
            return;
        }

        #[allow(clippy::cast_precision_loss)]
        let bytes_downloaded = bytes_downloaded as f64;

        let sample_bps = bytes_downloaded / time_passed.as_secs_f64();
        if self.bytes_per_second == 0.0 {
            // First sample — seed the estimate directly.
            self.bytes_per_second = sample_bps;
        } else {
            self.bytes_per_second =
                self.alpha.mul_add(sample_bps, (1.0 - self.alpha) * self.bytes_per_second);
        }
    }

    /// Current smoothed bytes-per-second estimate.
    pub const fn bytes_per_second(&self) -> f64 {
        self.bytes_per_second
    }

    /// Estimated seconds remaining to download `bytes_remaining`.
    /// Returns `f64::INFINITY` if no speed data is available yet.
    pub fn estimate_remaining_secs(&self, bytes_remaining: u64) -> f64 {
        if self.bytes_per_second <= 0.0 {
            return f64::INFINITY;
        }

        #[allow(clippy::cast_precision_loss)]
        return bytes_remaining as f64 / self.bytes_per_second;
    }
}