// Generated by Claude.

use core::f64;
use std::time::Duration;

pub struct DownloadSpeedEstimator {
    /// Smoothed bytes per second (exponential moving average).
    bytes_per_second: f64,
    /// EMA smoothing factor in 0..=1. Lower values = smoother.
    alpha: f64,
}

impl DownloadSpeedEstimator {
    /// Create a new estimator.
    /// `alpha` controls how quickly the estimate reacts to new samples.
    /// A value around 0.2–0.3 works well for download progress bars.
    pub const fn new(alpha: f64) -> Self {
        Self {
            bytes_per_second: 0.0,
            alpha: alpha.clamp(0.0, 1.0),
        }
    }

    /// Feed a sample of (`bytes_downloaded`, `time_passed`) for the most recent interval.
    /// `time_passed` is in seconds.
    fn update(&mut self, bytes_downloaded: usize, time_passed: Duration) -> Result<(), Error> {
        if time_passed <= Duration::ZERO {
            return Err(Error::TimeIsNotPositive);
        }

        let Ok(bytes_downloaded) = u32::try_from(bytes_downloaded) else {
            return Err(Error::ChunkIsTooBig);
        };

        let bytes_downloaded = f64::from(bytes_downloaded);

        let sample_bps = bytes_downloaded / time_passed.as_secs_f64();
        if self.bytes_per_second == 0.0 {
            // First sample — seed the estimate directly.
            self.bytes_per_second = sample_bps;
        } else {
            self.bytes_per_second =
                sample_bps.mul_add(self.alpha, self.bytes_per_second * (1.0 - self.alpha));
        }

        Ok(())
    }

    pub fn try_update(&mut self, bytes_downloaded: usize, time_passed: Duration) {
        if let Err(e) = self.update(bytes_downloaded, time_passed) {
            log::error!("Cannot update estimator: {:?}", e);
        }
    }

    /// Current smoothed bytes-per-second estimate.
    pub const fn bytes_per_second(&self) -> f64 {
        self.bytes_per_second
    }

    /// Estimated milliseconds remaining to download `bytes_remaining`.
    pub fn time_remaining(&self, bytes_remaining: u64) -> Result<Option<f64>, Error> {
        if bytes_remaining > 0xf_ffff_ffff_ffff {
            return Err(Error::FileIsTooBig);
        }

        if self.bytes_per_second <= 0.0 {
            return Ok(None);
        }

        let Ok(bytes_remaining_low) = u32::try_from(bytes_remaining & 0xffff_ffff) else {
            return Err(Error::Impossible);
        };

        let Ok(bytes_remining_high) = u32::try_from(bytes_remaining >> 32) else {
            return Err(Error::Impossible);
        };

        let bytes_remaining =
            f64::from(bytes_remining_high).mul_add(4_294_967_296.0, f64::from(bytes_remaining_low));

        let seconds_remaining = bytes_remaining / self.bytes_per_second;
        Ok(Some(seconds_remaining * 1000.0))
    }
}

#[derive(Debug)]
pub enum Error {
    ChunkIsTooBig,
    FileIsTooBig,
    Impossible,
    TimeIsNotPositive,
}
