// Generated by Claude.

use core::f64;
use std::time::Duration;

pub struct DownloadSpeedEstimator {
    /// Smoothed bytes per second (exponential moving average).
    bytes_per_second: f64,
    /// EMA smoothing factor in 0..=1. Lower values = smoother.
    alpha: f64,
}

impl DownloadSpeedEstimator {
    /// Create a new estimator.
    /// `alpha` controls how quickly the estimate reacts to new samples.
    /// A value around 0.2–0.3 works well for download progress bars.
    pub const fn new(alpha: f64) -> Self {
        Self {
            bytes_per_second: 0.0,
            alpha: alpha.clamp(0.0, 1.0),
        }
    }

    /// Feed a sample of (`bytes_downloaded`, `time_passed`) for the most recent interval.
    /// `time_passed` is in seconds.
    fn update(&mut self, bytes_downloaded: u64, time_passed: Duration) -> Result<(), Error> {
        if time_passed <= Duration::ZERO {
            return Err(Error::TimeIsNotPositive);
        }

        let bytes_downloaded = u64_to_f64_lossy(bytes_downloaded);
        let sample_bps = bytes_downloaded / time_passed.as_secs_f64();

        if self.bytes_per_second == 0.0 {
            // First sample — seed the estimate directly.
            self.bytes_per_second = sample_bps;
        } else {
            self.bytes_per_second =
                sample_bps.mul_add(self.alpha, self.bytes_per_second * (1.0 - self.alpha));
        }

        Ok(())
    }

    pub fn try_update(&mut self, bytes_downloaded: u64, time_passed: Duration) {
        if let Err(e) = self.update(bytes_downloaded, time_passed) {
            log::error!("Cannot update estimator: {:?}", e);
        }
    }

    /// Current smoothed bytes-per-second estimate.
    pub const fn bytes_per_second(&self) -> f64 {
        self.bytes_per_second
    }

    /// Estimated milliseconds remaining to download `bytes_remaining`.
    pub fn time_remaining(&self, bytes_remaining: u64) -> Option<f64> {
        if self.bytes_per_second <= 0.0 {
            return None;
        }

        let bytes_remaining = u64_to_f64_lossy(bytes_remaining);
        let seconds_remaining = bytes_remaining / self.bytes_per_second;
        Some(seconds_remaining * 1000.0)
    }
}

// It's okay here, because we don't need exact estimation
#[allow(clippy::cast_precision_loss)]
#[inline]
const fn u64_to_f64_lossy(x: u64) -> f64 {
    x as f64
}

#[derive(Debug)]
pub enum Error {
    ChunkIsTooBig,
    Impossible,
    TimeIsNotPositive,
}
