name: Upload artifacts to S3

inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
  s3-bucket:
    required: true
  target-dir:
    required: true
  project-path:
    required: false
    default: src-tauri

runs:
  using: "composite"
  steps:
    - name: Upload artifacts
      shell: bash
      run: |
        set -e

        upload_file() {
          local file="$1"
          local s3_path="$2"
          if [[ -f "$file" ]]; then
            echo "Uploading: $file"
            aws s3 cp --no-progress "$file" "$s3_path"
          else
            echo "Skipping: $file does not exist"
          fi
        }

        export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
        export AWS_DEFAULT_REGION="${{ inputs.aws-region }}"

        PROJECT_PATH="${{ inputs.project-path }}"
        BUNDLES=$(echo '${{ toJson(matrix.bundles) }}' | jq -r '.[]')
        EXTENSIONS="exe tar.gz dmg"

        detected_version=$(find "$PROJECT_PATH" -type f -name 'Decentraland_*_*' | head -n1 | sed -E 's/^.*Decentraland_([0-9]+\.[0-9]+\.[0-9]+)_.*/\1/')
        echo "Detected version: $detected_version"

        for bundle in $BUNDLES; do
          ARTIFACT_DIR="$PROJECT_PATH/target/release/bundle/$bundle"
          if [[ -d "$ARTIFACT_DIR" ]]; then
          echo "Renaming artifacts in $ARTIFACT_DIR"

            for file in "$ARTIFACT_DIR"/*; do
              if [[ -f "$file" && "$file" == *"Decentraland_${detected_version}_"* ]]; then
                filename=$(basename "$file")
                cleaned_name="${filename/Decentraland_${detected_version}_/Decentraland_}"
                echo "Renaming $filename -> $cleaned_name"
                mv "$ARTIFACT_DIR/$filename" "$ARTIFACT_DIR/$cleaned_name"
              fi
            done

            cd "$ARTIFACT_DIR"
            echo "Uploading artifacts from $ARTIFACT_DIR"
            for ext in $EXTENSIONS; do
              for file in *.$ext; do
                upload_file "$file" "s3://${{ inputs.s3-bucket }}/${{ inputs.target-dir }}/$file"
              done
            done
            cd -
          fi
        done

        DOMAIN="https://explorer-artifacts.decentraland.org"
        TARGET_PATH="launcher-rust"
        FILENAME_TAR="Decentraland.app.tar.gz"
        FILENAME_EXE="Decentraland_x64-setup.exe"

        if [[ -f "./latest.json" ]]; then
          echo "Found latest.json at ./latest.json"

          jq --arg tar_url "$DOMAIN/$TARGET_PATH/$FILENAME_TAR" \
             --arg exe_url "$DOMAIN/$TARGET_PATH/$FILENAME_EXE" \
            '.platforms["darwin-aarch64"].url = $tar_url |
             .platforms["windows-x86_64"].url = $exe_url' \
            ./latest.json > ./latest.json.tmp

          mv ./latest.json.tmp ./latest.json
          echo "Updated URLs in latest.json:"
          cat ./latest.json
        fi

        upload_file "./latest.json" "s3://${{ inputs.s3-bucket }}/${{ inputs.target-dir }}/latest.json"
