name: Upload artifacts to S3

inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
  s3-bucket:
    required: true
  target-dir:
    required: true
  project-path:
    required: false
    default: src-tauri

runs:
  using: "composite"
  steps:
    - name: Upload artifacts
      shell: bash
      run: |
        set -euo pipefail

        upload_file() {
          local file="$1"
          local s3_path="$2"
          if [[ -f "$file" ]]; then
            echo "Uploading: $file"
            aws s3 cp --no-progress "$file" "$s3_path"
          else
            echo "Skipping: $file does not exist"
          fi
        }

        export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
        export AWS_DEFAULT_REGION="${{ inputs.aws-region }}"

        PROJECT_PATH="${{ inputs.project-path }}"
        BUNDLES=$(echo '${{ toJson(matrix.bundles) }}' | jq -r '.[]')

        detected_version=$(find "$PROJECT_PATH" -type f -name 'Decentraland_*_*' | head -n1 | sed -E 's/^.*Decentraland_([0-9]+\.[0-9]+\.[0-9]+)_.*/\1/')
        echo "Detected version: $detected_version"

        for bundle in $BUNDLES; do
          ARTIFACT_DIR="$PROJECT_PATH/target/release/bundle/$bundle"
          if [[ -d "$ARTIFACT_DIR" ]]; then
            echo "Renaming artifacts in $ARTIFACT_DIR"

            for file in "$ARTIFACT_DIR"/*; do
              if [[ -f "$file" && "$file" == *"Decentraland_${detected_version}_"* ]]; then
                filename=$(basename "$file")
                cleaned_name="${filename/Decentraland_${detected_version}_/Decentraland_}"
                echo "Renaming $filename -> $cleaned_name"
                mv "$ARTIFACT_DIR/$filename" "$ARTIFACT_DIR/$cleaned_name"
              fi
            done

            # Windows -> Decentraland_installer.exe
            win_src="$(ls "$ARTIFACT_DIR"/Decentraland_*setup.exe 2>/dev/null | head -n1 || true)"
            if [[ -z "$win_src" ]]; then
              win_src="$(ls "$ARTIFACT_DIR"/Decentraland_*.exe 2>/dev/null | head -n1 || true)"
            fi
            if [[ -n "$win_src" ]]; then
              cp -f "$win_src" "$ARTIFACT_DIR/Decentraland_installer.exe"
            fi

            # macOS -> Decentraland_installer.dmg
            mac_src="$(ls "$ARTIFACT_DIR"/Decentraland_*.dmg 2>/dev/null | head -n1 || true)"
            if [[ -n "$mac_src" ]]; then
              cp -f "$mac_src" "$ARTIFACT_DIR/Decentraland_installer.dmg"
            fi

            # Upload dcl_launcher.exe directly from source dir
            upload_file "$PROJECT_PATH/target/release/dcl_launcher.exe" "s3://${{ inputs.s3-bucket }}/${{ inputs.target-dir }}/dcl_launcher.exe"

            # Upload the rest of the artifacts from the bundle dir
            cd "$ARTIFACT_DIR"
            echo "Uploading artifacts from $ARTIFACT_DIR"
            for file in Decentraland_installer.exe Decentraland_installer.dmg Decentraland.app.tar.gz; do
              upload_file "$file" "s3://${{ inputs.s3-bucket }}/${{ inputs.target-dir }}/$file"
            done
            cd -
          fi
        done

        DOMAIN="https://explorer-artifacts.decentraland.org"
        TARGET_PATH="launcher-rust"
        FILENAME_TAR="Decentraland.app.tar.gz"
        FILENAME_EXE="Decentraland_installer.exe"

        if [[ -f "./latest.json" ]]; then
          echo "Found latest.json at ./latest.json"

          jq --arg tar_url "$DOMAIN/$TARGET_PATH/$FILENAME_TAR" \
             --arg exe_url "$DOMAIN/$TARGET_PATH/$FILENAME_EXE" \
            '.platforms["darwin-aarch64"].url = $tar_url |
             .platforms["windows-x86_64"].url = $exe_url' \
            ./latest.json > ./latest.json.tmp

          mv ./latest.json.tmp ./latest.json
          echo "Updated URLs in latest.json:"
          cat ./latest.json
        fi

        upload_file "./latest.json" "s3://${{ inputs.s3-bucket }}/${{ inputs.target-dir }}/latest.json"
