name: Manual Release

on:
  workflow_dispatch:

concurrency:
  group: manual-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft_release:
    permissions:
      contents: write # Allows this job to create releases
    uses: ./.github/workflows/release.yml
    with:
      dry-run: false
    secrets:
      # Secrets required to sign and notarize the app in MacOS
      MACOS_CSC_LINK: ${{ secrets.MACOS_CSC_LINK }}
      MACOS_CSC_KEY_PASSWORD: ${{ secrets.MACOS_CSC_KEY_PASSWORD }}
      MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
      MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
      MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
      # Secrets required to sign and notarize the app in Windows
      ES_USERNAME: ${{ secrets.ES_USERNAME }}
      ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
      WINDOWS_CREDENTIAL_ID_SIGNER: ${{ secrets.WINDOWS_CREDENTIAL_ID_SIGNER }}
      ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
      # Segment API Key
      SEGMENT_API_KEY: ${{ secrets.SEGMENT_API_KEY }}
      # Sentry AUTH Token
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      # AWS Secrets
      EXPLORER_TEAM_S3_BUCKET: ${{ secrets.EXPLORER_TEAM_S3_BUCKET }}
      # Tauri Secrets
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
