name: Tests
on:
  workflow_call:
    inputs:
      should_run_tests_and_release:
        required: false
        type: string
        default: "true"

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Early exit if not required
        run: |
          if [ "${{ inputs.should_run_tests_and_release }}" != "true" ]; then
            echo "Skipping tests because should_run_tests_and_release != true"
            exit 0
          fi

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run test:main --if-present
      - run: npm run test:preload --if-present
      - run: npm run test:renderer --if-present
      # - run: npm run test:e2e --if-present
